# Use C++.
language: cpp
# Building for Linux.
os: linux
# Use Ubuntu Trusty 14.04.
dist: trusty
# Use sudo, because it's needed for Docker.
sudo: required
# Use Docker, for a newer Ubuntu container.
services: docker
# Install the dependencies.
install: "./CI/Travis/Linux/InstallDeps.sh"
# Build the program, in a Docker container.
script: "./CI/Travis/Linux/StartDockerBuild.sh"
