# Use C++.
language: cpp
jobs:
  include:
    # Analysis stage.
    - stage: analysis
      # Lints code with ClangFormat.
      env: NAME="ClangFormat Lint"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-format-6.0
      script: "./CI/Travis/Linux/ClangFormat.sh"
    # Analysis stage.
    - stage: analysis
      # Builds documentation with Doxygen.
      env: NAME="Doxygen Developer Documentation Build"
      addons:
        apt:
          # Install Doxygen, to generate the documentation.
          packages: doxygen
      # Generate the documentation. The Doxyfile will be configured to quit upon any errors.
      script: "./CI/Travis/Linux/BuildDevDocs.sh"
    # Code building stage.
    - stage: build
      # Compiles code for Linux.
      env: NAME="Linux Build"
      # Use sudo, because it's needed for Docker.
      sudo: required
      # Use Docker, for a newer Ubuntu container.
      services: docker
      # Install the dependencies.
      install: "./CI/Travis/Linux/InstallDeps.sh"
      # Build the program, in a Docker container.
      script: "./CI/Travis/Linux/StartDockerBuild.sh"
      # TODO: Deploy the developer documentation, and release to GitHub.
